### ISSUE TITLE
OSError: cannot load library 'libportaudio.so.2': /home/mypath/miniconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libjack.so.0)

### ISSUE THREAD

**Issue by TheWavePrinciple** [Lex-au/Orpheus-FastAPI#51]
Hi I can't figure this out, am going around in circles trying to work out this error. I have latest version of the missing library on my system I can see it from inside the venv?

Installed python 3.8.5 and set to system default.

Intel I5
8GB ram
GTX1060
SSD
Kali Linux

I'm having to change numpy to latest version in requirements file to get the install to complete everything.

(base) ┌──(venv)─(USER㉿MYPC)-[~/CODE/Orpheus-FastAPI]
└─$ python app.py
✅ Created default .env file from .env.example and environment variables.
Traceback (most recent call last):
  File "/home/mypath/CODE/Orpheus-FastAPI/app.py", line 54, in <module>
    from tts_engine import generate_speech_from_api, AVAILABLE_VOICES, DEFAULT_VOICE, VOICE_TO_LANGUAGE, AVAILABLE_LANGUAGES
  File "/home/mypath/CODE/Orpheus-FastAPI/tts_engine/__init__.py", line 10, in <module>
    from .inference import (
  File "/home/mypath/CODE/Orpheus-FastAPI/tts_engine/inference.py", line 8, in <module>
    import sounddevice as sd
  File "/home/mypath/CODE/Orpheus-FastAPI/venv/lib/python3.12/site-packages/sounddevice.py", line 72, in <module>
    _lib = _ffi.dlopen(_libname)
           ^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library 'libportaudio.so.2': /home/mypath/miniconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libjack.so.0)

Every time I run it I get this error!

From install.

(base) ┌──(USER㉿MYPC)-[~/CODE]
└─$ git clone https://github.com/Lex-au/Orpheus-FastAPI.git
cd Orpheus-FastAPI
Cloning into 'Orpheus-FastAPI'...
remote: Enumerating objects: 178, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 178 (delta 73), reused 48 (delta 48), pack-reused 87 (from 1)
Receiving objects: 100% (178/178), 13.18 MiB | 34.17 MiB/s, done.
Resolving deltas: 100% (87/87), done.
                                                                                                                   
(base) ┌──(USER㉿MYPC)-[~/CODE/Orpheus-FastAPI]
└─$ python -m venv venv
source venv/bin/activate  
                                                                                                                   
(base) ┌──(venv)─(USER㉿MYPC)-[~/CODE/Orpheus-FastAPI]
└─$ pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
Looking in indexes: https://download.pytorch.org/whl/cu124
Collecting torch
  Downloading https://download.pytorch.org/whl/cu124/torch-2.6.0%2Bcu124-cp312-cp312-linux_x86_64.whl.metadata (28 kB)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cu124/torchvision-0.21.0%2Bcu124-cp312-cp312-linux_x86_64.whl.metadata (6.1 kB)
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cu124/torchaudio-2.6.0%2Bcu124-cp312-cp312-linux_x86_64.whl.metadata (6.6 kB)
Collecting filelock (from torch)
  Downloading https://download.pytorch.org/whl/filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading https://download.pytorch.org/whl/typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting networkx (from torch)
  Downloading https://download.pytorch.org/whl/networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Collecting jinja2 (from torch)
  Downloading https://download.pytorch.org/whl/Jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch)
  Downloading https://download.pytorch.org/whl/fsspec-2024.6.1-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 32.2 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 23.0 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 31.6 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 27.5 MB/s eta 0:00:00
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 31.2 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 33.0 MB/s eta 0:00:00
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 32.5 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 32.3 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 32.9 MB/s eta 0:00:00
Collecting nvidia-cusparselt-cu12==0.6.2 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.21.5 (from torch)
  Downloading https://download.pytorch.org/whl/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 32.9 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading https://download.pytorch.org/whl/cu124/nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 29.2 MB/s eta 0:00:00
Collecting triton==3.2.0 (from torch)
  Downloading https://download.pytorch.org/whl/triton-3.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.4 kB)
Collecting setuptools (from torch)
  Downloading https://download.pytorch.org/whl/setuptools-70.2.0-py3-none-any.whl.metadata (5.8 kB)
Collecting sympy==1.13.1 (from torch)
  Using cached https://download.pytorch.org/whl/sympy-1.13.1-py3-none-any.whl (6.2 MB)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch)
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting numpy (from torchvision)
  Downloading https://download.pytorch.org/whl/numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Downloading https://download.pytorch.org/whl/pillow-11.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28 kB)
Downloading https://download.pytorch.org/whl/cu124/torch-2.6.0%2Bcu124-cp312-cp312-linux_x86_64.whl (768.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 768.4/768.4 MB 26.3 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/cu124/nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl (150.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.1/150.1 MB 32.9 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/triton-3.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (166.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.7/166.7 MB 32.9 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/cu124/torchvision-0.21.0%2Bcu124-cp312-cp312-linux_x86_64.whl (7.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 24.3 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/cu124/torchaudio-2.6.0%2Bcu124-cp312-cp312-linux_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 29.2 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/pillow-11.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (4.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 30.2 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading https://download.pytorch.org/whl/filelock-3.13.1-py3-none-any.whl (11 kB)
Downloading https://download.pytorch.org/whl/fsspec-2024.6.1-py3-none-any.whl (177 kB)
Downloading https://download.pytorch.org/whl/Jinja2-3.1.4-py3-none-any.whl (133 kB)
Downloading https://download.pytorch.org/whl/networkx-3.3-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 27.2 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 32.0 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/setuptools-70.2.0-py3-none-any.whl (930 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 930.8/930.8 kB 24.0 MB/s eta 0:00:00
Installing collected packages: triton, nvidia-cusparselt-cu12, mpmath, typing-extensions, sympy, setuptools, pillow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, MarkupSafe, fsspec, filelock, nvidia-cusparse-cu12, nvidia-cudnn-cu12, jinja2, nvidia-cusolver-cu12, torch, torchvision, torchaudio
Successfully installed MarkupSafe-2.1.5 filelock-3.13.1 fsspec-2024.6.1 jinja2-3.1.4 mpmath-1.3.0 networkx-3.3 numpy-2.1.2 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-cusparselt-cu12-0.6.2 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 pillow-11.0.0 setuptools-70.2.0 sympy-1.13.1 torch-2.6.0+cu124 torchaudio-2.6.0+cu124 torchvision-0.21.0+cu124 triton-3.2.0 typing-extensions-4.12.2
                                                                                                                   
(base) ┌──(venv)─(USER㉿MYPC)-[~/CODE/Orpheus-FastAPI]
└─$ pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
Looking in indexes: https://download.pytorch.org/whl/cu124
Requirement already satisfied: torch in ./venv/lib/python3.12/site-packages (2.6.0+cu124)
Requirement already satisfied: torchvision in ./venv/lib/python3.12/site-packages (0.21.0+cu124)
Requirement already satisfied: torchaudio in ./venv/lib/python3.12/site-packages (2.6.0+cu124)
Requirement already satisfied: filelock in ./venv/lib/python3.12/site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in ./venv/lib/python3.12/site-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in ./venv/lib/python3.12/site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in ./venv/lib/python3.12/site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in ./venv/lib/python3.12/site-packages (from torch) (2024.6.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in ./venv/lib/python3.12/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in ./venv/lib/python3.12/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in ./venv/lib/python3.12/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./venv/lib/python3.12/site-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in ./venv/lib/python3.12/site-packages (from torch) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in ./venv/lib/python3.12/site-packages (from torch) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in ./venv/lib/python3.12/site-packages (from torch) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in ./venv/lib/python3.12/site-packages (from torch) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in ./venv/lib/python3.12/site-packages (from torch) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in ./venv/lib/python3.12/site-packages (from torch) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in ./venv/lib/python3.12/site-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in ./venv/lib/python3.12/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in ./venv/lib/python3.12/site-packages (from torch) (12.4.127)
Requirement already satisfied: triton==3.2.0 in ./venv/lib/python3.12/site-packages (from torch) (3.2.0)
Requirement already satisfied: setuptools in ./venv/lib/python3.12/site-packages (from torch) (70.2.0)
Requirement already satisfied: sympy==1.13.1 in ./venv/lib/python3.12/site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./venv/lib/python3.12/site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in ./venv/lib/python3.12/site-packages (from torchvision) (2.1.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./venv/lib/python3.12/site-packages (from torchvision) (11.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.12/site-packages (from jinja2->torch) (2.1.5)
                                                                                                                   
(base) ┌──(venv)─(USER㉿MYPC)-[~/CODE/Orpheus-FastAPI]
└─$ pip3 install -r requirements.txt
Collecting fastapi==0.103.1 (from -r requirements.txt (line 2))
  Downloading fastapi-0.103.1-py3-none-any.whl.metadata (24 kB)
Collecting uvicorn==0.23.2 (from -r requirements.txt (line 3))
  Downloading uvicorn-0.23.2-py3-none-any.whl.metadata (6.2 kB)
Collecting jinja2==3.1.2 (from -r requirements.txt (line 4))
  Downloading Jinja2-3.1.2-py3-none-any.whl.metadata (3.5 kB)
Collecting pydantic==2.3.0 (from -r requirements.txt (line 5))
  Downloading pydantic-2.3.0-py3-none-any.whl.metadata (148 kB)
Collecting python-multipart==0.0.6 (from -r requirements.txt (line 6))
  Downloading python_multipart-0.0.6-py3-none-any.whl.metadata (2.5 kB)
Collecting requests==2.31.0 (from -r requirements.txt (line 9))
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting python-dotenv==1.0.0 (from -r requirements.txt (line 10))
  Downloading python_dotenv-1.0.0-py3-none-any.whl.metadata (21 kB)
Collecting watchfiles==1.0.4 (from -r requirements.txt (line 11))
  Downloading watchfiles-1.0.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting numpy==1.24.0 (from -r requirements.txt (line 14))
  Downloading numpy-1.24.0.tar.gz (10.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 21.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/mypath/CODE/Orpheus-FastAPI/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/mypath/CODE/Orpheus-FastAPI/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/mypath/CODE/Orpheus-FastAPI/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/home/mypath/CODE/Orpheus-FastAPI/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/mypath/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 999, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-9bs4dj2_/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-9bs4dj2_/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-9bs4dj2_/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
                                                                                                                   
(base) ┌──(venv)─(USER㉿MYPC)-[~/CODE/Orpheus-FastAPI]
└─$ pip3 install -r requirements.txt
Collecting fastapi==0.103.1 (from -r requirements.txt (line 2))
  Using cached fastapi-0.103.1-py3-none-any.whl.metadata (24 kB)
Collecting uvicorn==0.23.2 (from -r requirements.txt (line 3))
  Using cached uvicorn-0.23.2-py3-none-any.whl.metadata (6.2 kB)
Collecting jinja2==3.1.2 (from -r requirements.txt (line 4))
  Using cached Jinja2-3.1.2-py3-none-any.whl.metadata (3.5 kB)
Collecting pydantic==2.3.0 (from -r requirements.txt (line 5))
  Using cached pydantic-2.3.0-py3-none-any.whl.metadata (148 kB)
Collecting python-multipart==0.0.6 (from -r requirements.txt (line 6))
  Using cached python_multipart-0.0.6-py3-none-any.whl.metadata (2.5 kB)
Collecting requests==2.31.0 (from -r requirements.txt (line 9))
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting python-dotenv==1.0.0 (from -r requirements.txt (line 10))
  Using cached python_dotenv-1.0.0-py3-none-any.whl.metadata (21 kB)
Collecting watchfiles==1.0.4 (from -r requirements.txt (line 11))
  Using cached watchfiles-1.0.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting numpy==2.2.5 (from -r requirements.txt (line 14))
  Downloading numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting sounddevice==0.4.6 (from -r requirements.txt (line 15))
  Downloading sounddevice-0.4.6-py3-none-any.whl.metadata (1.4 kB)
Collecting snac==1.2.1 (from -r requirements.txt (line 16))
  Downloading snac-1.2.1-py3-none-any.whl.metadata (3.5 kB)
Collecting psutil==5.9.0 (from -r requirements.txt (line 19))
  Downloading psutil-5.9.0.tar.gz (478 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting anyio<4.0.0,>=3.7.1 (from fastapi==0.103.1->-r requirements.txt (line 2))
  Using cached anyio-3.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting starlette<0.28.0,>=0.27.0 (from fastapi==0.103.1->-r requirements.txt (line 2))
  Using cached starlette-0.27.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in ./venv/lib/python3.12/site-packages (from fastapi==0.103.1->-r requirements.txt (line 2)) (4.12.2)
Collecting click>=7.0 (from uvicorn==0.23.2->-r requirements.txt (line 3))
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Collecting h11>=0.8 (from uvicorn==0.23.2->-r requirements.txt (line 3))
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.12/site-packages (from jinja2==3.1.2->-r requirements.txt (line 4)) (2.1.5)
Collecting annotated-types>=0.4.0 (from pydantic==2.3.0->-r requirements.txt (line 5))
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.6.3 (from pydantic==2.3.0->-r requirements.txt (line 5))
  Downloading pydantic_core-2.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)
Collecting charset-normalizer<4,>=2 (from requests==2.31.0->-r requirements.txt (line 9))
  Using cached charset_normalizer-3.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (35 kB)
Collecting idna<4,>=2.5 (from requests==2.31.0->-r requirements.txt (line 9))
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests==2.31.0->-r requirements.txt (line 9))
  Downloading urllib3-2.4.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests==2.31.0->-r requirements.txt (line 9))
  Downloading certifi-2025.4.26-py3-none-any.whl.metadata (2.5 kB)
Collecting CFFI>=1.0 (from sounddevice==0.4.6->-r requirements.txt (line 15))
  Using cached cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: torch in ./venv/lib/python3.12/site-packages (from snac==1.2.1->-r requirements.txt (line 16)) (2.6.0+cu124)
Collecting einops (from snac==1.2.1->-r requirements.txt (line 16))
  Downloading einops-0.8.1-py3-none-any.whl.metadata (13 kB)
Collecting huggingface-hub (from snac==1.2.1->-r requirements.txt (line 16))
  Downloading huggingface_hub-0.30.2-py3-none-any.whl.metadata (13 kB)
Collecting sniffio>=1.1 (from anyio<4.0.0,>=3.7.1->fastapi==0.103.1->-r requirements.txt (line 2))
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting pycparser (from CFFI>=1.0->sounddevice==0.4.6->-r requirements.txt (line 15))
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Requirement already satisfied: filelock in ./venv/lib/python3.12/site-packages (from huggingface-hub->snac==1.2.1->-r requirements.txt (line 16)) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in ./venv/lib/python3.12/site-packages (from huggingface-hub->snac==1.2.1->-r requirements.txt (line 16)) (2024.6.1)
Collecting packaging>=20.9 (from huggingface-hub->snac==1.2.1->-r requirements.txt (line 16))
  Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pyyaml>=5.1 (from huggingface-hub->snac==1.2.1->-r requirements.txt (line 16))
  Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting tqdm>=4.42.1 (from huggingface-hub->snac==1.2.1->-r requirements.txt (line 16))
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: networkx in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (3.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (12.4.127)
Requirement already satisfied: triton==3.2.0 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (3.2.0)
Requirement already satisfied: setuptools in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (70.2.0)
Requirement already satisfied: sympy==1.13.1 in ./venv/lib/python3.12/site-packages (from torch->snac==1.2.1->-r requirements.txt (line 16)) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./venv/lib/python3.12/site-packages (from sympy==1.13.1->torch->snac==1.2.1->-r requirements.txt (line 16)) (1.3.0)
Downloading fastapi-0.103.1-py3-none-any.whl (66 kB)
Downloading uvicorn-0.23.2-py3-none-any.whl (59 kB)
Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
Downloading pydantic-2.3.0-py3-none-any.whl (374 kB)
Downloading python_multipart-0.0.6-py3-none-any.whl (45 kB)
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Downloading watchfiles-1.0.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (452 kB)
Downloading numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 31.3 MB/s eta 0:00:00
Downloading sounddevice-0.4.6-py3-none-any.whl (31 kB)
Downloading snac-1.2.1-py3-none-any.whl (8.4 kB)
Downloading pydantic_core-2.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 25.5 MB/s eta 0:00:00
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached anyio-3.7.1-py3-none-any.whl (80 kB)
Downloading certifi-2025.4.26-py3-none-any.whl (159 kB)
Using cached cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (479 kB)
Using cached charset_normalizer-3.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (145 kB)
Using cached click-8.1.8-py3-none-any.whl (98 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached starlette-0.27.0-py3-none-any.whl (66 kB)
Downloading urllib3-2.4.0-py3-none-any.whl (128 kB)
Downloading einops-0.8.1-py3-none-any.whl (64 kB)
Downloading huggingface_hub-0.30.2-py3-none-any.whl (481 kB)
Downloading packaging-25.0-py3-none-any.whl (66 kB)
Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (767 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.5/767.5 kB 21.4 MB/s eta 0:00:00
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: psutil
  Building wheel for psutil (pyproject.toml) ... done
  Created wheel for psutil: filename=psutil-5.9.0-cp312-cp312-linux_x86_64.whl size=230682 sha256=d9bf434a5ca844b7fcf4bc3452fdb95a57d822617c8662fed1ba6bcaf656231d
  Stored in directory: /home/mypath/.cache/pip/wheels/86/bf/4d/f133d3cbffc7c8991cd85fec43d18ff7507b3bc9042bbfd146
Successfully built psutil
Installing collected packages: urllib3, tqdm, sniffio, pyyaml, python-multipart, python-dotenv, pydantic-core, pycparser, psutil, packaging, numpy, jinja2, idna, h11, einops, click, charset-normalizer, certifi, annotated-types, uvicorn, requests, pydantic, CFFI, anyio, watchfiles, starlette, sounddevice, huggingface-hub, snac, fastapi
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.2
    Uninstalling numpy-2.1.2:
      Successfully uninstalled numpy-2.1.2
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.1.4
    Uninstalling Jinja2-3.1.4:
      Successfully uninstalled Jinja2-3.1.4
Successfully installed CFFI-1.17.1 annotated-types-0.7.0 anyio-3.7.1 certifi-2025.4.26 charset-normalizer-3.4.1 click-8.1.8 einops-0.8.1 fastapi-0.103.1 h11-0.16.0 huggingface-hub-0.30.2 idna-3.10 jinja2-3.1.2 numpy-2.2.5 packaging-25.0 psutil-5.9.0 pycparser-2.22 pydantic-2.3.0 pydantic-core-2.6.3 python-dotenv-1.0.0 python-multipart-0.0.6 pyyaml-6.0.2 requests-2.31.0 snac-1.2.1 sniffio-1.3.1 sounddevice-0.4.6 starlette-0.27.0 tqdm-4.67.1 urllib3-2.4.0 uvicorn-0.23.2 watchfiles-1.0.4

[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: pip install --upgrade pip
                                                                                                                   
(base) ┌──(venv)─(USER㉿MYPC)-[~/CODE/Orpheus-FastAPI]
└─$ # Create directories for outputs and static files
mkdir -p outputs static
                                                                                                                   
(base) ┌──(venv)─(USER㉿MYPC)-[~/CODE/Orpheus-FastAPI]
└─$ python app.py
✅ Created default .env file from .env.example and environment variables.
Traceback (most recent call last):
  File "/home/mypath/CODE/Orpheus-FastAPI/app.py", line 54, in <module>
    from tts_engine import generate_speech_from_api, AVAILABLE_VOICES, DEFAULT_VOICE, VOICE_TO_LANGUAGE, AVAILABLE_LANGUAGES
  File "/home/mypath/CODE/Orpheus-FastAPI/tts_engine/__init__.py", line 10, in <module>
    from .inference import (
  File "/home/mypath/CODE/Orpheus-FastAPI/tts_engine/inference.py", line 8, in <module>
    import sounddevice as sd
  File "/home/mypath/CODE/Orpheus-FastAPI/venv/lib/python3.12/site-packages/sounddevice.py", line 72, in <module>
    _lib = _ffi.dlopen(_libname)
           ^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library 'libportaudio.so.2': /home/mypath/miniconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libjack.so.0)

**Comment by TheWavePrinciple** [comment]
It's working on Windows and Linux but it turned out the linux build didn't have support for AVX2? But yeah everything worked thanks for the assist. I've generated some speech now. Great program thanks.
