### ISSUE TITLE
Problem using RTX 5060 Ti & Docker install

### ISSUE THREAD

**Issue by bisonbet** [Lex-au/Orpheus-FastAPI#69]
Hello.  I'm including the logs below, but I'm pretty sure the cuda/pytorch libraries just needed updated to work with the new GPU I have (5060ti).  I am going to take a look when I have a chance, but I wanted to put this issue here so someone else could also take a look. (Things work fine for 3060 and 3090)

✅ Created default .env file from .env.example and environment variables.
/app/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:235: UserWarning: 
NVIDIA GeForce RTX 5060 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5060 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
🖥️ Hardware: High-end CUDA GPU detected
📊 Device: NVIDIA GeForce RTX 5060 Ti
📊 VRAM: 15.49 GB
📊 Compute Capability: 12.0
🚀 Using high-performance optimizations
Configuration loaded:
  API_URL: http://llama-cpp-server:5006/v1/completions
  MAX_TOKENS: 8192
  TEMPERATURE: 0.6
  TOP_P: 0.9
  REPETITION_PENALTY: 1.1
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5005 (Press CTRL+C to quit)
Starting speech generation for 'Hello!  I'm happy to see you here.  '
Using voice: zoe, GPU acceleration: Yes (High-end)
Generating speech for: <|audio|>zoe: Hello!  I'm happy to see you here.  <|eot_id|>
Using optimized parameters for high-end GPU
Progress: 0.0 tokens/sec, est. 0.0s audio generated, 1 tokens, 0 chunks in 32.4s
Token processing rate: 0.0 tokens/second
Processing first audio chunk with 7 tokens
Error in token processing: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/app/tts_engine/inference.py", line 475, in async_producer
    async for audio_chunk in tokens_decoder(async_token_gen()):
  File "/app/tts_engine/inference.py", line 409, in tokens_decoder
    audio_samples = convert_to_audio(buffer_to_proc, count)
  File "/app/tts_engine/inference.py", line 363, in convert_to_audio
    result = orpheus_convert_to_audio(multiframe, count)
  File "/app/tts_engine/speechpipe.py", line 73, in convert_to_audio
    codes_0 = torch.zeros(num_frames, dtype=torch.int32, device=snac_device)
RuntimeError: CUDA error: no kernel image is available for execution on the device
Producer completed - setting done event
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Received end-of-stream marker
Waiting for token processor thread to complete...
Audio saved to outputs/zoe_20250709_004322.wav
Total speech generation completed in 32.54 seconds
INFO:     172.18.0.1:49346 - "POST /speak HTTP/1.1" 200 OK
INFO:     172.18.0.1:49346 - "GET /zoe_20250709_004322.wav HTTP/1.1" 200 OK

**Comment by Patwrick** [comment]
Had the same problem on the RTX 5080, seems to be working fine on my machine now (windows 11), try these 2 simple changes:

In Dockerfile.gpu (line 32) needs to include cu128 not cu124, like so:
"RUN pip3 install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128 && \"

In requirements.txt (line 23) needs to do the same, change to cu128, like so:
"#   pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128"

Basically just change "cu124" to "cu128" in both files...

Afterwards delete your existing container/image and run the command below, in the docker terminal (I'm using docker desktop):
"docker compose -f docker-compose-gpu.yml up --build -d"

**Comment by Lex-au** [comment]
Thanks for handling this one @Patwrick

**Comment by Lex-au** [comment]
@bisonbet Did the issue resolve for you with changing the CUDA version for your Blackwell card?

**Comment by corran7** [comment]
I had the same issue on Blackwell and the suggested fix worked for me.

<img width="1529" height="488" alt="Image" src="https://github.com/user-attachments/assets/fe466add-9c47-4ad2-8841-65d48515c8d5" />

**Comment by bisonbet** [comment]
> [@bisonbet](https://github.com/bisonbet) Did the issue resolve for you with changing the CUDA version for your Blackwell card?

Hello @Lex-au - yes.  I made the change and it worked fine after.  I added a PR here: https://github.com/Lex-au/Orpheus-FastAPI/pull/72

It's working for me personally.
